# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 719a574e40878ccd6e32174fda49696c0aac228bf4053e0d4521b99de2975d256ca29797ab31116cf52162f7d5afceadf27b4c295e95d10b302d2317a0ae893a

test:
  secret_key_base: 062734876a3546bc2391d9f5b9278cdbb6e540f93c8ac1e45a627b36a954a0b56921c96c69779b31f120b719449e98823dec8e70b9f155d91ecacb73bd7f7b2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
